baseURL = 'https://blog.chrisguest.dev/'
languageCode = 'en-us'
title = 'Blog'
theme = 'hugo-theme-codex'

enableEmoji = true

[params]
  twitter = "https://twitter.com/guestchris"
  github = "https://github.com/chrisguest75"
  # ...

  iconOrder = ["Twitter", "GitHub"]
  showPageTitleInTOC = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "personal"
  name = "personal"
  title = "personal"
  url = "/personal"

[[menu.main]]
  identifier = "examples"
  name = "examples"
  title = "examples"
  url = "/examples"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"