baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-theme-codex'



[params]
  twitter = "https://twitter.com/guestchris"
  github = "https://github.com/chrisguest75"
  # ...

  iconOrder = ["Twitter", "GitHub"]
  showPageTitleInTOC = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"