name: Build Blog

on:
  push:
    branches: 
      - '*'
      - '!main'   # excludes main
    paths:
      - '**'
      - '.github/workflows/build-deploy.yaml'

  pull_request:
    branches:  
      - '*'
      - '!main'   # excludes main
    paths:
      - '**'
      - '.github/workflows/build-deploy.yaml'

jobs:
  build-test:
    name: "Build Blog"  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'      

    - name: Build with hugo
      run: |
        echo "Installing Hugo"
        brew install hugo        
        echo "Running Hugo"
        cd quickstart
        hugo -D
        echo "COMPLETE exitcode:$?"

    - name: Publish 
      run: |
        echo "Sync Repo"
        ls -l 
        pwd
        mkdir -p ./target
        cd ./target
        git clone https://github.com/chrisguest75/pages_example.git
        cd pages_example
        rm -rf *   
        cp -R ../quickstart/public/* . 
        git checkout head -- README.md 
        git checkout head -- CNAME
        git add .
        git commit -m "From https://github.com/chrisguest75/hugo_examples ${{ github.sha }}"
        git push 

    # - name: Create build.json
    #   run: | 
    #     export COMMITID="${{ github.sha }}"
    #     cat ./src/build.template | envsubst > ./src/build.json          

