name: Build Blog

on:
  push:
    branches: 
      - '*'
      - '!main'   # excludes main
    paths:
      - '**'
      - '.github/workflows/build-deploy.yaml'

  pull_request:
    branches:  
      - '*'
      - '!main'   # excludes main
    paths:
      - '**'
      - '.github/workflows/build-deploy.yaml'

jobs:
  build-test:
    name: "Build Blog"  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'      

    - name: Build with hugo
      run: |
        echo "Installing Hugo"
        brew install hugo        
        echo "Running Hugo"
        cd quickstart
        hugo -D
        echo "COMPLETE exitcode:$?"

    - name: Publish 
      run: |
        pwd
        ls -la 
        echo "Sync Repo"
        mkdir -p ./target
        cd ./target
        git clone https://github.com/chrisguest75/pages_example.git
        cd pages_example
        echo "Remove files"
        rm -rf ./*   
        pwd
        ls -la .
        ls -la ../../
        echo "Copy files"
        cp -R ../../quickstart/public/* . 
        ls -la ./
        git status
        echo "Restore files"
        git checkout HEAD -- README.md 
        git checkout HEAD -- CNAME
        ls -la ./        
        git status
        echo "Add files"
        git add -A
        echo "Commit files"
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"        
        git commit -m "From https://github.com/chrisguest75/hugo_examples ${{ github.sha }}"
        git push origin main

    # - name: Create build.json
    #   run: | 
    #     export COMMITID="${{ github.sha }}"
    #     cat ./src/build.template | envsubst > ./src/build.json          

